name = "FieldAlgebra"
uuid = "0b62d163-fd1d-4060-a953-4385d03545e2"
authors = ["Michael Reed"]
version = "0.1.0"

[deps]
UnitSystems = "3a241a3c-2137-41aa-af5e-1388e404ca09"
AbstractTensors = "a8e43f4a-99b7-5565-8bf1-0165161caaea"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SyntaxTree = "a4af3ec5-f8ac-5fed-a759-c2e80b4d74cb"

[compat]
AbstractTensors = "0.7"
UnitSystems = "0.3.3"
SyntaxTree = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
